linters:
  disable-all: true
  enable:
    - contextcheck
    - errcheck
    - errorlint
    - gocritic
    - mnd
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nestif
    - nilerr
    - nilnil
    - revive
    - staticcheck
    - typecheck
    - unused
    - wastedassign

issues:
  exclude-dirs:
    - "terraform"
run:
  timeout: 5m

output:
  formats:
    - format: colored-line-number
      path: stdout
    - format: junit-xml
      path: modron-lint.xml
