version: '3'

services:
  modron_proxy:
    container_name: modron_proxy
    image: envoyproxy/envoy:v1.24-latest
    volumes:
      - ./docker/envoyproxy:/etc/envoy
    ports:
      - "8080:10000"
    networks:
      - modron
    depends_on:
      - modron_ui
      - modron_fake

  modron_fake:
    container_name: modron_fake
    build: src/
    environment:
      PORT: 8080
      STORAGE: "MEM"
      COLLECTOR: "FAKE"
      ORG_ID: "0123456789"
      ORG_SUFFIX: "@example.com"
      GRPC_VERBOSITY: "DEBUG"
      GRPC_TRACE: "all"
    networks:
      - modron

  modron_ui:
    container_name: modron_ui
    build: ./src/ui
    environment:
      ENVIRONMENT: "E2E_TESTING"
      DIST_PATH: "./ui"
      PORT: 8080
    networks:
      - modron

  modron_test:
    container_name: modron_test
    build:
      context: ./src/ui/client
      dockerfile: Dockerfile.e2e
    depends_on:
      - modron_proxy
    environment:
      CYPRESS_BASE_URL: "http://modron_proxy:10000"
    command: npx cypress run
    volumes:
      - ./src/ui/client/cypress:/app/cypress:ro
      - ./docker/cypress/tsconfig.json:/app/tsconfig.json
      - ./docker/cypress/cypress.config.ts:/app/cypress.config.ts
    networks:
      - modron

volumes:
  stats:
    external: false

networks:
  modron:
    driver: bridge
