// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	GetNotificationException(ctx context.Context, in *GetNotificationExceptionRequest, opts ...grpc.CallOption) (*NotificationException, error)
	CreateNotificationException(ctx context.Context, in *CreateNotificationExceptionRequest, opts ...grpc.CallOption) (*NotificationException, error)
	UpdateNotificationException(ctx context.Context, in *UpdateNotificationExceptionRequest, opts ...grpc.CallOption) (*NotificationException, error)
	DeleteNotificationException(ctx context.Context, in *DeleteNotificationExceptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListNotificationExceptions(ctx context.Context, in *ListNotificationExceptionsRequest, opts ...grpc.CallOption) (*ListNotificationExceptionsResponse, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) GetNotificationException(ctx context.Context, in *GetNotificationExceptionRequest, opts ...grpc.CallOption) (*NotificationException, error) {
	out := new(NotificationException)
	err := c.cc.Invoke(ctx, "/NotificationService/GetNotificationException", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateNotificationException(ctx context.Context, in *CreateNotificationExceptionRequest, opts ...grpc.CallOption) (*NotificationException, error) {
	out := new(NotificationException)
	err := c.cc.Invoke(ctx, "/NotificationService/CreateNotificationException", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) UpdateNotificationException(ctx context.Context, in *UpdateNotificationExceptionRequest, opts ...grpc.CallOption) (*NotificationException, error) {
	out := new(NotificationException)
	err := c.cc.Invoke(ctx, "/NotificationService/UpdateNotificationException", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) DeleteNotificationException(ctx context.Context, in *DeleteNotificationExceptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/NotificationService/DeleteNotificationException", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) ListNotificationExceptions(ctx context.Context, in *ListNotificationExceptionsRequest, opts ...grpc.CallOption) (*ListNotificationExceptionsResponse, error) {
	out := new(ListNotificationExceptionsResponse)
	err := c.cc.Invoke(ctx, "/NotificationService/ListNotificationExceptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility
type NotificationServiceServer interface {
	GetNotificationException(context.Context, *GetNotificationExceptionRequest) (*NotificationException, error)
	CreateNotificationException(context.Context, *CreateNotificationExceptionRequest) (*NotificationException, error)
	UpdateNotificationException(context.Context, *UpdateNotificationExceptionRequest) (*NotificationException, error)
	DeleteNotificationException(context.Context, *DeleteNotificationExceptionRequest) (*emptypb.Empty, error)
	ListNotificationExceptions(context.Context, *ListNotificationExceptionsRequest) (*ListNotificationExceptionsResponse, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNotificationServiceServer struct {
}

func (UnimplementedNotificationServiceServer) GetNotificationException(context.Context, *GetNotificationExceptionRequest) (*NotificationException, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotificationException not implemented")
}
func (UnimplementedNotificationServiceServer) CreateNotificationException(context.Context, *CreateNotificationExceptionRequest) (*NotificationException, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNotificationException not implemented")
}
func (UnimplementedNotificationServiceServer) UpdateNotificationException(context.Context, *UpdateNotificationExceptionRequest) (*NotificationException, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNotificationException not implemented")
}
func (UnimplementedNotificationServiceServer) DeleteNotificationException(context.Context, *DeleteNotificationExceptionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNotificationException not implemented")
}
func (UnimplementedNotificationServiceServer) ListNotificationExceptions(context.Context, *ListNotificationExceptionsRequest) (*ListNotificationExceptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNotificationExceptions not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_GetNotificationException_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotificationExceptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetNotificationException(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NotificationService/GetNotificationException",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetNotificationException(ctx, req.(*GetNotificationExceptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateNotificationException_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNotificationExceptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateNotificationException(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NotificationService/CreateNotificationException",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateNotificationException(ctx, req.(*CreateNotificationExceptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_UpdateNotificationException_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNotificationExceptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).UpdateNotificationException(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NotificationService/UpdateNotificationException",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).UpdateNotificationException(ctx, req.(*UpdateNotificationExceptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_DeleteNotificationException_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNotificationExceptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).DeleteNotificationException(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NotificationService/DeleteNotificationException",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).DeleteNotificationException(ctx, req.(*DeleteNotificationExceptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_ListNotificationExceptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotificationExceptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).ListNotificationExceptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NotificationService/ListNotificationExceptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).ListNotificationExceptions(ctx, req.(*ListNotificationExceptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNotificationException",
			Handler:    _NotificationService_GetNotificationException_Handler,
		},
		{
			MethodName: "CreateNotificationException",
			Handler:    _NotificationService_CreateNotificationException_Handler,
		},
		{
			MethodName: "UpdateNotificationException",
			Handler:    _NotificationService_UpdateNotificationException_Handler,
		},
		{
			MethodName: "DeleteNotificationException",
			Handler:    _NotificationService_DeleteNotificationException_Handler,
		},
		{
			MethodName: "ListNotificationExceptions",
			Handler:    _NotificationService_ListNotificationExceptions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification.proto",
}
